### ISSUE TITLE
allow pin based input/output configuration instead of patitioning

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-StateGPIO-ESP32-FW#2]

**Comment by moinmoin-sh** [comment]
Brainstorming:

Instead of having the enum to configure a starting GPIO, we could use an edit box where the user has to enter a comma seperated list of GPIOs which to configure as output. With that we have the I/O config seperated and it would become effective after reboot.
Downside : we can't validate a string on UI level, would be parsed and validated on the ESP

or
we create a list of checkboxes (1 for each available GPIO) which the user checks. Reboot to make effective.
Downside: long list (16 items) at the top of the page and adopt payload increases

**Comment by sumnerboy12** [comment]
Why don't you like the idea of an array of config objects, one per pin? The config would include the pin number, I/O type, and any I/O specific config.

**Comment by moinmoin-sh** [comment]
I see the need for a config per GPIO, but don't like the resulting AdminUI config page with all options for input and output listed for each pin. I don't expect a quick fix for the AdminUI, but wanted to provide a FW with the pin based I/O config while keeping a clean config page.

**Comment by sumnerboy12** [comment]
Implemented in new repo - https://github.com/OXRS-IO/OXRS-IO-DigitalIO-ESP32-FW
